- src: https://github.com/lueschem/fluentbit_installer.git
  version: c795105db7d2ada813beb6d8f25e92e02edfe5b1
- src: https://github.com/lueschem/ansible-kiosk.git
  version: b213c938f3a84f12929fb0caeef1db8c7ee404e5
- src: https://github.com/MonolithProjects/ansible-github_actions_runner.git
  version: 1.17.0
- src: https://github.com/lueschem/edi_installer.git
  version: 1.0.0
